### ISSUE TITLE
Adapter rework ideas and notes

### ISSUE THREAD

**Issue by BenediktBurger** [bmoneke/pymeasure#1]
Ideas and notes about Adapter rework.

Phases
=====

1. Adding tests for instruments
2. Reworking official adapters, Instrument class and adjust tests, documentation, and all instruments to these changes. (not here)
4. Add a Test Generator
5. Rework some adapters proper to some instruments and maybe some official adapters

Open questions
----------------

Adapter rework
==========
General
--------
- [ ] Include a test generator which generates tests out of device communication (code written)
- [ ] Test generator documentation
- [x] add a BaseChannel with dynamic properties (initial code written)
- [ ] `Instrument` may ask in the setter instead of write only (initial code written)
- [ ] Make a SCPI Instrument?

Instruments and special adapters
====================

Special Adapters move, if possible, to default adapters
----------------
- [ ] attocube and anc300 https://github.com/pymeasure/pymeasure/pull/835
- [x] danfysik and danfysik8500: should be removable, verify, that it works as expected.
- [x] lakeshore: could be moved to pyvisa, I guess (code written)
- [ ] Oxford Adapter: move it to its own superclass between Instrument and the specific instrument itself.
- [x] Toptica: move to instrument itself. (code already written. For new PR)
- [ ] Remove these instruments from the "test_all_instruments" exception for proper adapters.

Test special adapters change
-----------------------------
- [ ] attocube
- [x] danfysik
- [x] lakeshore
- [ ] Oxford
- [x] Toptica

Test Generator
---------------
- [ ] handle testing several times the same property/setter but with different values: keep the same name (what does pytest do?) or numerate them? Possibility to give a list of values to test for a parametrized test?
- [ ] handle the byte value b"\n" correctly

Instruments overhaul
----------------------
- [x] TC038D move to pymeasure properties (code written)

Clean up
-----------

Issues and discussions
==============
- https://github.com/pymeasure/pymeasure/issues/567 Main issue
- https://github.com/pymeasure/pymeasure/issues/512 contains more connected issues
- https://github.com/pymeasure/pymeasure/issues/409
- https://github.com/pymeasure/pymeasure/issues/506 Regarding thread-safety and its difficulties. Questionable whether it should be included here
- https://github.com/pymeasure/pymeasure/issues/219

**Comment by bmoneke** [comment]
Now in https://github.com/pymeasure/pymeasure/pull/660

**Comment by BenediktBurger** [comment]
Mostly done or moved to single issues.
