### ISSUE TITLE
feedback on generator for instrument tests 

### ISSUE THREAD

**Issue by LongnoseRob** [bmoneke/pymeasure#3]
As mentioned in pymeasure/pymeasure#752 I tried  `pymeasure/tests/generator.py` with the HP3478A multimeter conencted by GPIB.
The file I used for creating the tests is [TG_HP3478A.txt](https://github.com/bmoneke/pymeasure/files/10072490/TG_HP3478A.txt)
the result file is [test_hp3478a.txt](https://github.com/bmoneke/pymeasure/files/10072494/test_hp3478a.txt)
As is now with some lines commented-out works and pytest passes without issues.

Items noted:

1. the test-file is opened but not automatically written if following your example. to get it working in my spyder-IDE, I added the line 57 `g.__del__()`  _(The lines following are only to properly close the log)_
2. `test_method()` does not work on calls with methods which does not return anything or only return a non-callable
  - example 1 (method without return value): `g.test_method("display_text", "ABCDEFGHIJKL")` will trhow a LookupError:
    ```
    11:50:49 AM: Test method display_text. (generator, INFO)
    []
    [b'WRITE:B\n', b'READ:\xc5\x1f\x00\x00%\n']
    Traceback (most recent call last):
    
      File /usr/lib/python3.10/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
        exec(code, globals, locals)
    
      File ~/builds/pymeasure/tests/TG_HP3478A.py:27
        g.test_method("display_text", "ABCDEFGHIJKL")
    
      File ~/builds/pymeasure/tests/generator.py:195 in test_method
        value = getattr(self.instr, method)(*args, **kwargs)
    
      File ~/builds/pymeasure/pymeasure/instruments/instrument.py:211 in __getattribute__
        return super().__getattribute__(name)
    
      File ~/builds/pymeasure/pymeasure/instruments/instrument.py:429 in fget
        raise LookupError("Instrument property can not be read.")
    
    LookupError: Instrument property can not be read.
    ```
  - example 2 (method with non-callable return): `g.test_method("measure_ACI")`will throw the following TypeError:
    ```
    11:45:07 AM: Test method measure_ACI. (generator, INFO)
    11:45:07 AM: WRITE:F6 (Adapter, DEBUG)
    11:45:07 AM: GPIB.write b'F6\r\n' (pyvisa, DEBUG)
    11:45:07 AM: GPIB0::23::INSTR - reading 20480 bytes (last status <StatusCode.success_max_count_read: 1073676294>) (pyvisa, DEBUG)
    []
    [b'WRITE:B\n', b'READ:-\x1f\x00\x00%\n']
    11:45:10 AM: READ:+000.425E-3
     (Adapter, DEBUG)
    Traceback (most recent call last):
    
      File /usr/lib/python3.10/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
        exec(code, globals, locals)
    
      File ~/builds/pymeasure/tests/TG_HP3478A.py:29
        g.test_method("measure_ACI")
    
      File ~/builds/pymeasure/tests/generator.py:195 in test_method
        value = getattr(self.instr, method)(*args, **kwargs)
    
    TypeError: 'float' object is not callable
    ```
  - other methods (like `hp3478a.reset(), .GPIB_trigger` fail because of the use of calls to `adapter.`-methods (Corner case for non-SCPI instruments?)
3. Would it be possible and make sense  to implement something like 
 ` g.test_property_setter(bool_property, [True, False])` or 
 `g.test_property_setter(numerical_property, [0, 1, 2 .71, 3.14, 6.28, 23, 42]` ? 
 Or did I just overlook something and this is already possible?
4. flake8 has some feedback on test_hp3478a.py:
  ```
  $ flake8 test_hp3478a.py 
  test_hp3478a.py:26:41: E712 comparison to True should be 'if cond is True:' or 'if cond:'
  test_hp3478a.py:34:40: E712 comparison to True should be 'if cond is True:' or 'if cond:'
  test_hp3478a.py:45:1: F811 redefinition of unused 'test_auto_zero_enabled_setter' from line 37
  test_hp3478a.py:58:42: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
  test_hp3478a.py:74:38: E711 comparison to None should be 'if cond is None:'
  ```

Good work and please let me know if you need further details or want me to try other things.

**Comment by BenediktBurger** [comment]
Thanks for testing.

`test_method` is supposed to test methods, not properties, therefore `display_text` and `measure_ACI` failed. In this case you should use `test_property_setter` / `getter`, respectively.
If nothing is returned, yes, then it will fail (or it will create a stupid test `assert method_returning_None() == None`).

Yes, you can only test communication, which uses read/write (or their bytes versions). Adapter calls are ignored.

**Comment by BenediktBurger** [comment]
I improved the code. Thanks for giving feedback.
